const BASE = 'https://www.adiance.com';
const seoConfig = {
  home: { title: 'NDAA Compliant CCTV Camera Manufacturer | OEM & ODM | Adiance', description: 'NDAA-compliant CCTV manufacturer offering OEM/ODM white-label cameras with AI video analytics and edge AI for global security integrators.', canonicalUrl: `${BASE}/`, keywords: 'NDAA compliant camera manufacturer, OEM CCTV camera, ODM surveillance camera, white label CCTV, AI surveillance camera, edge AI camera' },
  about: { title: 'About Adiance | NDAA Compliant Camera Manufacturer Since 2003', description: 'Adiance Technologies has been manufacturing surveillance cameras since 2003. We offer NDAA-compliant, non-Chinese SoC cameras with in-house AI VMS and mobile app for global security markets.', canonicalUrl: `${BASE}/about`, keywords: 'Adiance Technologies, CCTV manufacturer India, surveillance camera company' },
  products: { title: 'CCTV Camera Products | AI-Powered Surveillance Cameras | Adiance', description: 'Explore Adiance CCTV camera range: edge AI cameras, PTZ cameras, bullet cameras, dome cameras, and NVRs. All NDAA-compliant with Qualcomm and Novatek chipsets.', canonicalUrl: `${BASE}/edgeaicamera`, keywords: 'edge AI camera, CCTV camera products, PTZ camera, bullet camera, dome camera, NVR' },
  oem: { title: 'OEM & White Label CCTV Camera Manufacturing | Adiance', description: 'Partner with Adiance for OEM and white-label CCTV camera manufacturing. Custom branding, firmware customization, NDAA compliance, and global shipping.', canonicalUrl: `${BASE}/oem-cctv-india`, keywords: 'OEM CCTV camera manufacturer, white label camera, private label surveillance' },
  innovation: { title: 'AI & Innovation in Surveillance | Edge AI Technology | Adiance', description: 'Adiance leads innovation in AI-powered surveillance with edge AI processing, smart video analytics, and next-generation camera technology.', canonicalUrl: `${BASE}/innovation`, keywords: 'AI surveillance innovation, edge AI camera technology, smart video analytics' },
  contact: { title: 'Contact Adiance | Get a Quote for CCTV Cameras & OEM Services', description: 'Contact Adiance for OEM/ODM CCTV camera quotes, white-label partnerships, or technical inquiries. Global manufacturer serving 30+ countries.', canonicalUrl: `${BASE}/contact`, keywords: 'contact CCTV manufacturer, get a quote CCTV camera, OEM camera inquiry' },
  blog: { title: 'Security Camera Blog | Industry Insights & Guides | Adiance', description: 'Expert articles on CCTV cameras, NDAA compliance, AI surveillance, OEM manufacturing from Adiance Technologies.', canonicalUrl: `${BASE}/blog`, keywords: 'CCTV camera blog, surveillance industry insights, NDAA compliance guide' },
  smartCities: { title: 'Smart City Surveillance Solutions | AI-Powered CCTV | Adiance', description: 'Adiance smart city surveillance solutions: AI-powered CCTV cameras, video analytics, traffic monitoring for municipal governments.', canonicalUrl: `${BASE}/smart-cities`, keywords: 'smart city surveillance, city CCTV camera, municipal security' },
  middleEast: { title: 'CCTV Camera Supplier for Middle East | NDAA Compliant | Adiance', description: 'Adiance supplies NDAA-compliant CCTV cameras to the Middle East market including UAE, Saudi Arabia, Qatar, and the broader GCC region.', canonicalUrl: `${BASE}/oem-camera-manufacturer-middle-east`, keywords: 'CCTV camera Middle East, surveillance camera UAE, Saudi Arabia CCTV' },
  europe: { title: 'CCTV Camera Manufacturer for Europe | GDPR Ready | Adiance', description: 'Adiance provides GDPR-ready, NDAA-compliant CCTV cameras for the European market. Non-Chinese manufactured surveillance solutions.', canonicalUrl: `${BASE}/cctv-manufacturer-europe`, keywords: 'CCTV camera Europe, GDPR compliant camera, surveillance camera EU' },
  oemPartner: { title: 'OEM/ODM Partner Program | White-Label CCTV Manufacturing | Adiance', description: 'Become an Adiance OEM/ODM partner. White-label CCTV camera manufacturing with NDAA compliance, custom firmware, your branding, and competitive pricing for distributors and security brands worldwide.', canonicalUrl: `${BASE}/oem-partner`, keywords: 'OEM partner program CCTV, white label camera manufacturer, NDAA compliant OEM, surveillance camera distributor, CCTV manufacturing partner' },
};
export default seoConfig;
